// Challenge list used by demo mode. The live app reads the Challenges database in Notion.
export const CHALLENGES = [
 {
  "id": "0",
  "emoji": "👋",
  "title": "Learn 3 names",
  "description": "Ask 3 strangers their name and remember it.",
  "tier": "Easy",
  "points": 15,
  "proof": "Instant",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "1",
  "emoji": "🙏",
  "title": "Ask “How can I pray for you?”",
  "description": "Ask someone and pray for them right then.",
  "tier": "Easy",
  "points": 25,
  "proof": "Instant",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "2",
  "emoji": "🌍",
  "title": "Meet a new nation",
  "description": "Talk with someone from a background you haven’t logged. Earns a Nations Passport stamp.",
  "tier": "Easy",
  "points": 20,
  "proof": "Instant",
  "limit": "Each nation once per season",
  "team": false,
  "gift": "",
  "passport": "Nations"
 },
 {
  "id": "12",
  "emoji": "📍",
  "title": "Stamp a new place",
  "description": "Pray or talk with someone in a kind of place you haven’t logged yet. Earns a Places Passport stamp.",
  "tier": "Easy",
  "points": 20,
  "proof": "Instant",
  "limit": "Each place once per season",
  "team": false,
  "gift": "",
  "passport": "Places"
 },
 {
  "id": "13",
  "emoji": "😊",
  "title": "Give a genuine compliment",
  "description": "Encourage a stranger, then ask if you can share what God says about them.",
  "tier": "Easy",
  "points": 10,
  "proof": "Instant",
  "limit": "5×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "14",
  "emoji": "🪑",
  "title": "Sit with someone",
  "description": "Ask to join someone sitting alone and have a real conversation.",
  "tier": "Easy",
  "points": 20,
  "proof": "Instant",
  "limit": "2×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "15",
  "emoji": "🧭",
  "title": "Ask a spiritual question",
  "description": "“What do you think happens after we die?” and listen well.",
  "tier": "Easy",
  "points": 20,
  "proof": "Instant",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "3",
  "emoji": "🤕",
  "title": "Pray for healing",
  "description": "Offer to pray for someone’s body. Log what happened.",
  "tier": "Medium",
  "points": 50,
  "proof": "Photo",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "4",
  "emoji": "🤳",
  "title": "Selfie with a new friend",
  "description": "Get a picture with someone you just met (with permission!).",
  "tier": "Medium",
  "points": 40,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "5",
  "emoji": "🎁",
  "title": "Random act of kindness",
  "description": "Give a coffee, water, or snack, then share why.",
  "tier": "Medium",
  "points": 35,
  "proof": "Photo",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "6",
  "emoji": "📖",
  "title": "Share your testimony",
  "description": "Tell someone your story in under 3 minutes.",
  "tier": "Medium",
  "points": 60,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "16",
  "emoji": "🗣️",
  "title": "Speak a new language",
  "description": "Greet someone in their heart language (“hello, God loves you”) and snap a photo of them smiling.",
  "tier": "Medium",
  "points": 45,
  "proof": "Photo",
  "limit": "1×/language",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "17",
  "emoji": "🧼",
  "title": "Serve with your hands",
  "description": "Pick up trash, carry groceries, help someone, then tell them why you did it.",
  "tier": "Medium",
  "points": 40,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "18",
  "emoji": "💧",
  "title": "Water bottle blessing",
  "description": "Hand out a Well water bottle with a blessing or invite card.",
  "tier": "Medium",
  "points": 30,
  "proof": "Photo",
  "limit": "5×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "19",
  "emoji": "📞",
  "title": "Get a number",
  "description": "Get a first name and a way to reach someone so you can follow up.",
  "tier": "Medium",
  "points": 45,
  "proof": "Photo",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "20",
  "emoji": "🎨",
  "title": "Prophetic picture or word",
  "description": "Share an encouraging word or picture for a stranger. Log how they responded.",
  "tier": "Medium",
  "points": 55,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "7",
  "emoji": "🧩",
  "title": "Team: 5 nations in 1 hour",
  "description": "As a team, talk with people from 5 different backgrounds in one outing.",
  "tier": "Medium",
  "points": 50,
  "proof": "Photo",
  "limit": "1×/day",
  "team": true,
  "gift": "",
  "passport": "Nations"
 },
 {
  "id": "21",
  "emoji": "🗺️",
  "title": "Team: 3 places, 1 outing",
  "description": "Together visit 3 different kinds of places and have a conversation in each.",
  "tier": "Medium",
  "points": 50,
  "proof": "Photo",
  "limit": "1×/day",
  "team": true,
  "gift": "",
  "passport": "Places"
 },
 {
  "id": "22",
  "emoji": "📸",
  "title": "Team photo flash mob",
  "description": "Whole team in one photo with someone you met, with their permission.",
  "tier": "Medium",
  "points": 40,
  "proof": "Photo",
  "limit": "1×/day",
  "team": true,
  "gift": "",
  "passport": ""
 },
 {
  "id": "8",
  "emoji": "✝️",
  "title": "Share the gospel start to finish",
  "description": "Walk someone through the good news and invite a response.",
  "tier": "Hard",
  "points": 120,
  "proof": "Leader approval",
  "limit": "3×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "9",
  "emoji": "🔁",
  "title": "Follow up within 48 hrs",
  "description": "Reach back out to someone you met and log what happened.",
  "tier": "Hard",
  "points": 90,
  "proof": "Leader approval",
  "limit": "Once per contact",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "10",
  "emoji": "🕊️",
  "title": "Pray with 3 people in one outing",
  "description": "Three prayers, three different people, one outing.",
  "tier": "Hard",
  "points": 100,
  "proof": "Leader approval",
  "limit": "1×/day",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "23",
  "emoji": "☕",
  "title": "Coffee with a contact",
  "description": "Meet someone you met in the field for a real conversation. Photo of the table, not of them.",
  "tier": "Hard",
  "points": 110,
  "proof": "Leader approval",
  "limit": "Once per contact",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "24",
  "emoji": "🏥",
  "title": "Visit the hurting",
  "description": "Visit someone in hospital, nursing home or at a shelter and pray with them.",
  "tier": "Hard",
  "points": 100,
  "proof": "Leader approval",
  "limit": "2×/week",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "25",
  "emoji": "🌐",
  "title": "Five nations, five gospel chats",
  "description": "Share the gospel with people from 5 different backgrounds this season.",
  "tier": "Hard",
  "points": 150,
  "proof": "Leader approval",
  "limit": "Once per season",
  "team": false,
  "gift": "",
  "passport": "Nations"
 },
 {
  "id": "26",
  "emoji": "🙌",
  "title": "Healing confirmed",
  "description": "Someone reports pain gone or improved after your prayer. Leader confirms by talking with them or watching the clip.",
  "tier": "Hard",
  "points": 130,
  "proof": "Leader approval",
  "limit": "3×/week",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "27",
  "emoji": "🤝",
  "title": "Team: Bring someone to church",
  "description": "A contact comes to a Well gathering or small group. Team gets the points.",
  "tier": "Hard",
  "points": 150,
  "proof": "Leader approval",
  "limit": "Once per contact",
  "team": true,
  "gift": "",
  "passport": ""
 },
 {
  "id": "11",
  "emoji": "👑",
  "title": "Someone says yes to Jesus",
  "description": "Lead someone in a prayer of salvation (leader confirms).",
  "tier": "Legendary",
  "points": 250,
  "proof": "Leader approval",
  "limit": "No cap, leader confirms each",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "28",
  "emoji": "💦",
  "title": "Baptism",
  "description": "Someone you led to Jesus gets baptized.",
  "tier": "Legendary",
  "points": 300,
  "proof": "Leader approval",
  "limit": "Once per person",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "29",
  "emoji": "🌱",
  "title": "Disciple-maker",
  "description": "Meet with a new believer 4 weeks in a row.",
  "tier": "Legendary",
  "points": 300,
  "proof": "Leader approval",
  "limit": "Once per person",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "30",
  "emoji": "🛂",
  "title": "Passport Complete",
  "description": "Stamp 25 countries on the Nations Passport, or fill the Places Passport.",
  "tier": "Legendary",
  "points": 200,
  "proof": "Leader approval",
  "limit": "Once per passport per season",
  "team": false,
  "gift": "",
  "passport": ""
 },
 {
  "id": "31",
  "emoji": "👁️",
  "title": "Word of knowledge",
  "description": "Ask God for a detail about a stranger (a body part, a name, a situation). Share it humbly and ask if it means anything to them.",
  "tier": "Medium",
  "points": 55,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "Knowledge",
  "passport": ""
 },
 {
  "id": "32",
  "emoji": "💬",
  "title": "Encourage with a prophetic word",
  "description": "Share a short, encouraging word for someone. Log how they responded. Keep it kind and testable.",
  "tier": "Medium",
  "points": 50,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "Prophecy",
  "passport": ""
 },
 {
  "id": "33",
  "emoji": "🔍",
  "title": "Discern a need",
  "description": "Sense that someone needs prayer or help before they say anything. Go ask. Log what you noticed.",
  "tier": "Medium",
  "points": 40,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "Discernment",
  "passport": ""
 },
 {
  "id": "34",
  "emoji": "🫶",
  "title": "Show mercy",
  "description": "Sit with someone who is hurting and just listen and pray. No agenda.",
  "tier": "Medium",
  "points": 45,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "Mercy",
  "passport": ""
 },
 {
  "id": "35",
  "emoji": "🏠",
  "title": "Open your table",
  "description": "Invite a new friend or contact for a meal or coffee (your treat).",
  "tier": "Medium",
  "points": 50,
  "proof": "Photo",
  "limit": "2×/week",
  "team": false,
  "gift": "Hospitality",
  "passport": ""
 },
 {
  "id": "36",
  "emoji": "💝",
  "title": "Give generously",
  "description": "Anonymously give money, food or a gift to someone in need and pray for them.",
  "tier": "Medium",
  "points": 45,
  "proof": "Photo",
  "limit": "3×/week",
  "team": false,
  "gift": "Giving",
  "passport": ""
 },
 {
  "id": "37",
  "emoji": "🎓",
  "title": "Teach a quick lesson",
  "description": "Explain one Bible truth or story to someone in 2 minutes (the Good Samaritan, the lost sheep, etc.).",
  "tier": "Medium",
  "points": 50,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "Teaching",
  "passport": ""
 },
 {
  "id": "38",
  "emoji": "🌬️",
  "title": "Pray in the Spirit",
  "description": "With permission, pray quietly in tongues over someone, then pray in English. Share what you sensed.",
  "tier": "Medium",
  "points": 40,
  "proof": "Photo",
  "limit": "2×/day",
  "team": false,
  "gift": "Tongues",
  "passport": ""
 },
 {
  "id": "39",
  "emoji": "⚡",
  "title": "Faith step",
  "description": "Do something that takes real faith: ask for a miracle, pray for the impossible. Log what happened.",
  "tier": "Hard",
  "points": 100,
  "proof": "Leader approval",
  "limit": "2×/week",
  "team": false,
  "gift": "Faith",
  "passport": ""
 },
 {
  "id": "40",
  "emoji": "🔮",
  "title": "Word that hit the mark",
  "description": "A word or picture you gave was confirmed (“How did you know that?”). Leader confirms.",
  "tier": "Hard",
  "points": 140,
  "proof": "Leader approval",
  "limit": "3×/week",
  "team": false,
  "gift": "Prophecy",
  "passport": ""
 },
 {
  "id": "41",
  "emoji": "🌟",
  "title": "Miracle report",
  "description": "Witness or see a miracle: healing of a visible condition, provision, deliverance. Share the testimony with a leader.",
  "tier": "Legendary",
  "points": 250,
  "proof": "Leader approval",
  "limit": "Leader confirms each",
  "team": false,
  "gift": "Miracles",
  "passport": ""
 },
 {
  "id": "42",
  "emoji": "🧠",
  "title": "Wisdom for a decision",
  "description": "Someone is stuck on a big decision. Pray with them and offer godly counsel. Log what you shared.",
  "tier": "Hard",
  "points": 90,
  "proof": "Leader approval",
  "limit": "2×/week",
  "team": false,
  "gift": "Wisdom",
  "passport": ""
 },
 {
  "id": "43",
  "emoji": "📣",
  "title": "Lead a stranger-team",
  "description": "Gather 2–3 people you just met and lead them in a short prayer or Bible moment.",
  "tier": "Hard",
  "points": 110,
  "proof": "Leader approval",
  "limit": "1×/week",
  "team": false,
  "gift": "Leadership",
  "passport": ""
 },
 {
  "id": "44",
  "emoji": "🧰",
  "title": "Serve a need quietly",
  "description": "Notice a practical need and meet it without being asked. Photo of the result, not the person.",
  "tier": "Medium",
  "points": 40,
  "proof": "Photo",
  "limit": "3×/day",
  "team": false,
  "gift": "Helps",
  "passport": ""
 },
 {
  "id": "45",
  "emoji": "🎁",
  "title": "Gift Explorer",
  "description": "Complete one challenge in 6 different gift categories this season to discover your gifting.",
  "tier": "Hard",
  "points": 120,
  "proof": "Leader approval",
  "limit": "Once per season",
  "team": false,
  "gift": "",
  "passport": ""
 }
];
